version: 2.1

executors:
    go:
        parameters:
            build_image:
                type: string
                default: "circleci/golang"
                description: Go build image
            go_version:
                type: string
                description: Go build image version
        docker:
            -   image: << parameters.build_image >>:<< parameters.go_version >>
                environment:
                    GOFLAGS: -mod=readonly
                    GOPROXY: https://proxy.golang.org

jobs:
    build:
        parameters:
            executor:
                type: executor
                default: "go"
        executor: << parameters.executor >>

        steps:
            - checkout

            -   restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

            -   run:
                    name: Download Go module cache
                    command: go mod download

            -   run:
                    name: Run tests
                    command: |
                        if [ $CIRCLE_NODE_TOTAL -gt 1 ]; then
                            export TEST_PKGS=$(echo `go list ./... | circleci tests split`)
                            export TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml
                        fi

                        make test

            -   save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

            -   store_test_results:
                    path: build/test_results/

workflows:
    build:
        jobs:
            -   build:
                    name: build-go1.11
                    executor:
                        name: go
                        go_version: "1.11"

            -   build:
                    name: build-go1.12
                    executor:
                        name: go
                        go_version: "1.12"

            -   build:
                    name: build-go1.13
                    executor:
                        name: go
                        go_version: "1.13beta1"
